### ISSUE TITLE
Eagle-Reader v0.15.0 from PyPi is missing latest source

### ISSUE THREAD

**Issue by gtdiehl** [jesserizzo/envoy_reader#25]
@jesserizzo The v0.15.0 release from PyPi is missing the latest source, for example `update()`.

Can you rebuild the package and bump the version number to something like v0.15.1?

I commented on the PR #22 where my code was pulled from but since it's Closed I wasn't sure if you'd see the comment.

Thanks!

**Comment by jesserizzo** [comment]
@gtdiehl Ok, I just made a new release 0.15.1.

**Comment by gtdiehl** [comment]
@jesserizzo Great, thank you!  I've opened a PR in HA to use the latest API and my updated sensor https://github.com/home-assistant/core/pull/32637
