### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by jesserizzo** [jesserizzo/envoy_reader#65]
@gtdiehl I'd like to rename the master branch to main, just want to make sure it won't screw up any in flight work. Looks like there's only 1 active PR, which will get automatically updated.

**Comment by gtdiehl** [comment]
@jesserizzo I don't see any issue with it.

**Comment by gtdiehl** [comment]
@jesserizzo I looked into renaming the default branch and it appears you can under `Settings` >> `Branches` and click on the pencil to rename the branch. I don't have access to the Settings, so you'd have to rename the default branch from `master` to `main`
